name: Render PDFs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-r@v2

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R dependencies
        run: Rscript -e 'install.packages("quarto", repos="https://cloud.r-project.org")'

      - name: Render
        run: Rscript render.R

      - name: Publish PDFs to output branch
        run: |
          git switch output
          git rm -rf .
          cp ../output/*.pdf .
          git add *.pdf
          git commit -m "Update rendered PDFs" || exit 0
          git push origin output
